services:
  app:
    image: ${APP_IMAGE:-}
    command: sh -c 'pnpm run:dev'
    restart: always
    container_name: prelude
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - ../src:/app/src
      - ../migrations:/app/migrations
    depends_on:
      - db
    expose:
      - "${APP_PORT:-8080}"

  db:
    image: postgres:15-alpine
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    expose:
      - "${POSTGRES_PORT:-5432}"
    command: -p "${POSTGRES_PORT:-5432}"

